### ISSUE TITLE
after install, globals are not initialised

### ISSUE THREAD

**Issue by estebanlm** [mtaborda/chalten#1]
Hi,

After doing a regular install as explained in README.md, globals (January..December, etc.) are not initialised :(

Eso :)

EDIT: I forget to say: in Pharo 5 (but it shouldn't be a problem, I think)

**Comment by mtaborda** [comment]
Hi Esteban,
The master branch is broken.
In a 5.x image, you must load the development branch.

Metacello new
    baseline: 'Chalten';
    githubUser: 'mtaborda' project: 'chalten' commitish: 'development' path: 'repository';
    load
